### ISSUE TITLE
List possible interactions

### ISSUE THREAD

**Issue by LeoJhonSong** [RTCS-Team25/Project#6]
Read trhough the api list and other documents to list up **reasonable**, **interesting** ineraction  methods. For example, pepper could even [identifies the emotion expressed by the speaker’s voice](https://developer.softbankrobotics.com/pepper-naoqi-25/naoqi-developer-guide/naoqi-apis/naoqi-audio/alvoiceemotionanalysis)!

**Comment by LeoJhonSong** [comment]
@maiahely Hi Maia couold you please skim the [NAOqi APIs](https://developer.softbankrobotics.com/pepper-naoqi-25/naoqi-developer-guide/naoqi-apis) to find out some interesting, uesful functions and list them here? For example, this [ALAnimatedSpeech](https://developer.softbankrobotics.com/pepper-naoqi-25/naoqi-developer-guide/naoqi-apis/naoqi-audio/alanimatedspeech) could quite interesting right! BTW, please drag this card to **In Progess** as soon as you start to do this. :+1:

**Comment by maiahely** [comment]
ALDiaolog groups together a list of rules to great conversational skills in the robot. However we are doing this slightly differently with our state switching model.

**ALVoiceEmotionAnalysis** would be an interesting one to explore if we have time as it could provide a deeper understanding of what the user is feeling rather than just through what they are saying.  It allows the robot to process and assign emotions at the end of a speech segment from the user.

**ALAnimatedSpeech** allows the robot to be expressive while talking which would be good to create a more realistic and reassuring interaction with he user.

**ALBasicAwareness** allows the user to track a human face once it has been detected, allowing eye contact to be maintained, giving the sense of engagement from the Pepper with the human

**ALMood** allows Pepper to detect the mood of the user without speech. Over 3 seconds it can register; “positive”, “neutral”, “negative”, “unknown”. It can take in the surroundings to tell whether the atmosphere is calm or excited based on noise levels which could direct which exercise we have the Pepper guide the user through. For example, if it is in an excited space we could show a video rather than doing a quiet mediation. This function also can determine the user's level of attention to Pepper.
